### ISSUE TITLE
no data available while have position 

### ISSUE THREAD

**Issue by krissnawat** [dinngo/compound-kit-api#23]
i have postion on Arbitrum 
![image](https://github.com/dinngo/compound-kit-api/assets/26294749/ce621618-43b7-42da-a5e1-2726fadc0dea)

then try on API . seem response with no position

![image](https://github.com/dinngo/compound-kit-api/assets/26294749/529f594a-5d6d-443e-9ae8-5f5c849b46e3)

**Comment by zodahu** [comment]
Hi @krissnawat 
Thank you for bringing this to our attention. Can I confirm if your position is in the circle native USDC market?
Currently, the compound-kit's USDC market still points to the bridged usdc.e market. We plan to update it soom to support both markets simultaneously.

**Comment by krissnawat** [comment]
thank for update 
It’s circle native

**Comment by zodahu** [comment]
@krissnawat
The compound-kit has been updated. You can retrieve the latest supported markets from https://compound-kit-api.protocolink.com/v1/markets.
- In the arbitrum market, the id `usdc` stands for native circle USDC.
- In the arbitrum market, the id `usdc.e` stands for bridged USDC.

**Comment by krissnawat** [comment]
> @krissnawat The compound-kit has been updated. You can retrieve the latest supported markets from https://compound-kit-api.protocolink.com/v1/markets.
> 
> * In the arbitrum market, the id `usdc` stands for native circle USDC.
> * In the arbitrum market, the id `usdc.e` stands for bridged USDC.

thankyou for fast update
